export const sampleBrands = [
  {
    id: 1,
    icon: '/assets/logo/brands/bmw.png',
    brandName: 'BMW',
    brandValue: 'bmw',
    count: 45,
  },
  {
    id: 2,
    icon: '/assets/logo/brands/ferrari.png',
    brandName: 'Ferrari',
    brandValue: 'ferrari',
    count: 32,
  },
  {
    id: 3,
    icon: '/assets/logo/brands/kia.png',
    brandName: 'Kia',
    brandValue: 'kia',
    count: 56,
  },
  {
    id: 4,
    icon: '/assets/logo/brands/lamborghini.png',
    brandName: 'Lamborghini',
    brandValue: 'lamborghini',
    count: 78,
  },
  {
    id: 5,
    icon: '/assets/logo/brands/land-rover.png',
    brandName: 'Land Rover',
    brandValue: 'land_rover',
    count: 23,
  },
  {
    id: 6,
    icon: '/assets/logo/brands/mercedes-benz.png',
    brandName: 'Mercedes-Benz',
    brandValue: 'mercedes-benz',
    count: 88,
  },
  {
    id: 7,
    icon: '/assets/logo/brands/nissan.png',
    brandName: 'Nissan',
    brandValue: 'nissan',
    count: 42,
  },
  {
    id: 8,
    icon: '/assets/logo/brands/porsche.png',
    brandName: 'Porsche',
    brandValue: 'porsche',
    count: 65,
  },
  {
    id: 9,
    icon: '/assets/logo/brands/rolls-royce.png',
    brandName: 'Rolls-Royce',
    brandValue: 'rolls-royce',
    count: 37,
  },
  {
    id: 10,
    icon: '/assets/logo/brands/jeep.png',
    brandName: 'Jeep',
    brandValue: 'jeep',
    count: 19,
  },
  {
    id: 11,
    icon: '/assets/logo/brands/toyota.png',
    brandName: 'Toyota',
    brandValue: 'toyota',
    count: 51,
  },
]
